# Git & identity (#210).
#
# Hybrid translation (ADR-0002): the global git config is generated by
# programs.git; hooks and ignores stay literal via xdg.configFile.
#
# Identity (user.name / user.email) is set by the identity modules
# (personal.nix / company.nix). The signing key is per-host and set
# in the host modules (pop-personal.nix / pop-company.nix) because it
# is bound to the per-machine YubiKey subkey (#211 / ADR-0003).
#
# This module retires config/git/config.local — the "machine subkey system"
# include is no longer needed once each host declares its own signingkey.
{ lib, pkgs, ... }:
let
  repoConfig = ../../config;
in
{
  programs.git = {
    enable = true;

    # user.name / user.email / user.signing.key are set by identity and host
    # modules respectively via programs.git.settings (mkDefault).

    signing = {
      format = "openpgp";
      signByDefault = true;
    };

    settings = {
      init.defaultBranch = "main";

      core.hooksPath = "~/.config/git/hooks";

      sequence.editor = "interactive-rebase-tool";

      # herdr provisions a worktree per task from the parent checkout's HEAD
      # without fetching or setting an upstream first (measured: every
      # herdr-created branch's reflog says "Created from HEAD", no fetch call
      # in its logic, no `branch.*.remote` set on a fresh worktree). These
      # five close the gap that leaves open, machine-wide:
      pull = {
        # a diverged pull fails loudly instead of creating a surprise
        # merge/rebase commit — rebase/merge stay explicit, human acts
        ff = "only";
      };
      fetch = {
        # remote-tracking refs for deleted PR branches don't linger as stale
        # [gone] noise between fetches
        prune = true;
      };
      push = {
        # herdr never sets an upstream; the first `git push` from a fresh
        # worktree branch would otherwise fail asking for `--set-upstream`
        autoSetupRemote = true;
      };
      rerere = {
        # the same conflict resolved once in one worktree doesn't have to be
        # re-solved by hand in a sibling worktree
        enabled = true;
      };
      merge = {
        # shows the common ancestor, not just both sides — materially better
        # for an agent resolving a conflict
        conflictStyle = "zdiff3";
      };

      # GitHub credential helpers (gh auth).
      "credential \"https://github.com\"" = {
        helper = [
          ""
          "!gh auth git-credential"
        ];
      };
      "credential \"https://gist.github.com\"" = {
        helper = [
          ""
          "!gh auth git-credential"
        ];
      };
    };

    ignores = [
      # OS generated files
      ".DS_Store"
      "Thumbs.db"

      # Editor files
      "*.swp"
      "*.swo"
      "*~"
      ".*.swp"
      "\\#*\\#"
      ".\\#*"

      # Temporary files
      "*.tmp"
      "*.bak"
      "*.backup"

      # IDE
      ".idea/"
      ".vscode/"

      # Claude local settings
      "**/.claude/settings.local.json"
    ];
  };

  # Literal hooks — placed verbatim under ~/.config/git/hooks.
  xdg.configFile."git/hooks/pre-push" = {
    source = repoConfig + "/git/hooks/pre-push";
    executable = true;
  };

  # core.hooksPath makes git skip .git/hooks/ for pre-commit too, so every
  # per-repo pre-commit (ruff/mypy via .pre-commit-config.yaml, etc.) was
  # silently inert. Chain to it the same way pre-push already does.
  xdg.configFile."git/hooks/pre-commit" = {
    source = repoConfig + "/git/hooks/pre-commit";
    executable = true;
  };
}
