# Git & identity (#210).
#
# Hybrid translation (ADR-0002): the global git config is generated by
# programs.git; hooks and ignores stay literal via xdg.configFile.
#
# Identity (user.name / user.email) is set by the identity modules
# (personal.nix / company.nix). The signing key is per-host and set
# in the host modules (pop-personal.nix / pop-company.nix) because it
# is bound to the per-machine YubiKey subkey (#211 / ADR-0003).
#
# This module retires config/git/config.local — the "machine subkey system"
# include is no longer needed once each host declares its own signingkey.
{ lib, pkgs, ... }:
let
  repoConfig = ../../config;
in
{
  programs.git = {
    enable = true;

    # user.name / user.email / user.signing.key are set by identity and host
    # modules respectively via programs.git.settings (mkDefault).

    signing = {
      format = "openpgp";
      signByDefault = true;
    };

    settings = {
      init.defaultBranch = "main";

      core.hooksPath = "~/.config/git/hooks";

      sequence.editor = "interactive-rebase-tool";

      alias = {
        prune-branches = "!f() { git fetch -p && git for-each-ref --merged=main --format='%(refname:short) %(upstream:track)' refs/heads | awk '$2 == \"[gone]\" {print $1}' | while IFS= read -r branch; do git branch -d -- \"$branch\"; done; }; f";
      };

      # GitHub credential helpers (gh auth).
      "credential \"https://github.com\"" = {
        helper = [
          ""
          "!gh auth git-credential"
        ];
      };
      "credential \"https://gist.github.com\"" = {
        helper = [
          ""
          "!gh auth git-credential"
        ];
      };
    };

    ignores = [
      # OS generated files
      ".DS_Store"
      "Thumbs.db"

      # Editor files
      "*.swp"
      "*.swo"
      "*~"
      ".*.swp"
      "\\#*\\#"
      ".\\#*"

      # Temporary files
      "*.tmp"
      "*.bak"
      "*.backup"

      # IDE
      ".idea/"
      ".vscode/"

      # Claude local settings
      "**/.claude/settings.local.json"
    ];
  };

  # Literal hooks — placed verbatim under ~/.config/git/hooks.
  xdg.configFile."git/hooks/pre-push" = {
    source = repoConfig + "/git/hooks/pre-push";
    executable = true;
  };

  # core.hooksPath makes git skip .git/hooks/ for pre-commit too, so every
  # per-repo pre-commit (ruff/mypy via .pre-commit-config.yaml, etc.) was
  # silently inert. Chain to it the same way pre-push already does.
  xdg.configFile."git/hooks/pre-commit" = {
    source = repoConfig + "/git/hooks/pre-commit";
    executable = true;
  };
}
